"""Golden-snapshot regression gate for the CPU-worker-optim spec.

Every commit under W1-W7 of the spec must pass these tests. The goldens
are generated by running the pre-change pipeline once (see
GENERATE_GOLDEN flag below). After that they are byte-checked.

Determinism policy (CRITICAL):
- The pipeline's default multiprocessing path is NOT bit-deterministic
  (vertex set drifts ~0.7% across runs — T0 finding 2026-04-17). The
  golden gate therefore forces `num_workers=1` via a `SerialPool`
  monkeypatch applied in the worker script.
- Running multiple fixtures in one Python process also breaks
  determinism (cuDNN/cuBLAS autotune cache + CUDA workspace are
  per-process and workload-dependent — diagnosed 2026-04-17: F3 output
  drifts ~0.9 in V depending on what ran before it in the process).
- Solution: each fixture runs in its own subprocess via
  `_cpu_worker_optim_runner.py`. PYTHONHASHSEED=0 is set in the
  subprocess env so stage `set`/`dict` iteration is fixed.

Tolerance policy:
- V / F scalar counts: exact match.
- Final mesh tensors (V×3 vertices, F×3 faces): max abs diff <= 1e-5
  (vertex positions) AND exact integer match (face indices).

Fixtures (F1, F2, F3):
- F1: res=128, icosphere subdiv=3
- F2: res=256, same mesh
- F3: res=128, triple-concentric icosphere (covers s7 multi-loop path)

Generate goldens once:
    GENERATE_GOLDEN=1 pytest corep_fast/tests/regression/test_cpu_worker_optim.py -v

Re-run the gate:
    pytest corep_fast/tests/regression/test_cpu_worker_optim.py -v

Regenerate only if out-of-scope code (s1/s2/s3 or external deps) changes.
"""
import os
import pickle
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
import pytest

GOLDEN_DIR = Path(__file__).parent / "cpu_worker_optim_goldens"
RUNNER = Path(__file__).parent / "_cpu_worker_optim_runner.py"
GENERATE = os.environ.get("GENERATE_GOLDEN") == "1"


FIXTURE_SPEC = [
    ("F1", 128, "icosphere_s3"),
    ("F2", 256, "icosphere_s3"),
    ("F3", 128, "triple_icosphere"),
]


def _golden_path(label: str, mesh_name: str, resolution: int) -> Path:
    return GOLDEN_DIR / f"{label}_{mesh_name}_r{resolution}.pkl"


def _run_pipeline_subprocess(label: str, mesh_name: str, resolution: int) -> dict:
    """Run one fixture in a fresh Python subprocess and return its V/F output.

    Isolates CUDA state — without this, cuDNN/cuBLAS autotune cache leaks
    across fixtures and F3 output becomes non-reproducible.
    """
    with tempfile.NamedTemporaryFile(suffix=".pkl", delete=False) as fh:
        out_path = fh.name
    try:
        env = os.environ.copy()
        env["PYTHONHASHSEED"] = "0"
        subprocess.run(
            [sys.executable, str(RUNNER),
             "--fixture", label,
             "--resolution", str(resolution),
             "--mesh-name", mesh_name,
             "--output", out_path],
            env=env, check=True,
        )
        with open(out_path, "rb") as fh:
            return pickle.load(fh)
    finally:
        Path(out_path).unlink(missing_ok=True)


@pytest.fixture(scope="session")
def _ensure_golden_dir():
    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)


@pytest.mark.parametrize("label,resolution,mesh_name", FIXTURE_SPEC,
                          ids=[f[0] for f in FIXTURE_SPEC])
def test_golden_snapshot(label, resolution, mesh_name, _ensure_golden_dir):
    """Compare current pipeline output to committed golden snapshot."""
    pkl_path = _golden_path(label, mesh_name, resolution)
    out = _run_pipeline_subprocess(label, mesh_name, resolution)

    if GENERATE or not pkl_path.exists():
        if not GENERATE:
            pytest.fail(
                f"Golden missing: {pkl_path}. Run with GENERATE_GOLDEN=1 "
                f"to create it (ONLY from baseline commit)."
            )
        with open(pkl_path, "wb") as fh:
            pickle.dump(out, fh)
        print(f"[GENERATE] wrote {pkl_path}")
        return

    with open(pkl_path, "rb") as fh:
        golden = pickle.load(fh)

    assert out["V_count"] == golden["V_count"], (
        f"V count drift: golden={golden['V_count']} new={out['V_count']}"
    )
    assert out["F_count"] == golden["F_count"], (
        f"F count drift: golden={golden['F_count']} new={out['F_count']}"
    )

    max_v_diff = float(np.abs(out["V"] - golden["V"]).max()) if out["V"].size else 0.0
    assert max_v_diff <= 1e-5, f"V position drift max={max_v_diff} > 1e-5"

    assert np.array_equal(out["F"], golden["F"]), "F index mismatch"
